// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using chatBotIaCore.Infra.DAL;

#nullable disable

namespace chatBotIaCore.Infra.Migrations
{
    [DbContext(typeof(ChatBotIaCoreContext))]
    [Migration("20251116214416_addFieldInBotSystemFixInThePromptAndINsertDataInThisNewField")]
    partial class addFieldInBotSystemFixInThePromptAndINsertDataInThisNewField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("chatBotIaCore.Domain.Models.BotConfiguration", b =>
                {
                    b.Property<int>("BotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("bot_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BotId"));

                    b.Property<DateTime?>("BotCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("bot_created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("BotMaxOutputTokenCount")
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("bot_Max_Output_Token_Count");

                    b.Property<string>("BotModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("bot_model_name");

                    b.Property<string>("BotName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("bot_name");

                    b.Property<bool>("BotSystemEnabled")
                        .ValueGeneratedOnAdd()
                        .IsUnicode(false)
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("bot_System_Enable");

                    b.Property<string>("BotSystemPrompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bot_system_prompt");

                    b.Property<string>("BotSystemPromptJsonResponse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bot_system_prompt_json_response");

                    b.Property<decimal>("BotTemperature")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3, 2)")
                        .HasDefaultValue(2m)
                        .HasColumnName("bot_temperature");

                    b.Property<DateTime?>("BotUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("bot_updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("BotId")
                        .HasName("PK__BotConfi__310884E0DA9B83A7");

                    b.ToTable("BotConfiguration", (string)null);

                    b.HasData(
                        new
                        {
                            BotId = 1,
                            BotCreatedAt = new DateTime(2025, 10, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            BotMaxOutputTokenCount = 4096,
                            BotModelName = "openai/gpt-4o-mini",
                            BotName = "Default Assistant",
                            BotSystemEnabled = true,
                            BotSystemPrompt = "You are a helpful and friendly AI conversational assistant. Your sole purpose is to process the current conversation context and respond EXCLUSIVELY with a valid JSON object. Follow these strict rules:\r\n\r\n1. Language:\r\n   - Your default response language is Portuguese-BR.\r\n   - If the user explicitly switches the language (e.g., to English or Spanish), you must reply in that language.\r\n\r\n2. Output Format:\r\n   - Your entire output must be a single JSON object that matches the LlmResponse schema defined by the system.\r\n   - Do not include any text, markdown blocks, code fences, or explanations outside the JSON object.\r\n\r\n3. Field Rules:\r\n   - textResponse: A helpful, concise conversational reply in the correct language. Markdown formatting is allowed inside the string.\r\n   - toolToUse: Must ALWAYS be an empty string (\"\").\r\n   - chatType:\r\n       - Use \"1\" for Ongoing.\r\n       - Use \"2\" for Ended.\r\n       - Only return \"2\" (Ended) when the conversation is clearly finished AND you have already confirmed with the user. Never end a conversation if there is no previous assistantMessage in the history.\r\n\r\nAlways return exactly one JSON object and nothing else.\r\n",
                            BotSystemPromptJsonResponse = "{\r\n                    \"type\": \"object\",\r\n                    \"properties\": {\r\n                        \"textResponse\": { \"type\": \"string\" },\r\n                        \"toolToUse\": { \"type\": \"string\" },\r\n                        \"chatType\": { \"type\": \"string\", \"enum\": [\"1\", \"2\"] }\r\n                    },\r\n                    \"required\": [\"textResponse\", \"toolToUse\", \"chatType\"],\r\n                    \"additionalProperties\": false\r\n                }",
                            BotTemperature = 0.7m,
                            BotUpdatedAt = new DateTime(2025, 10, 25, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("chatBotIaCore.Domain.Models.BotTool", b =>
                {
                    b.Property<int>("ToolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tool_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ToolId"));

                    b.Property<bool>("ToolActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("tool_active");

                    b.Property<DateTime?>("ToolCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("tool_created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ToolDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("tool_description");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tool_name");

                    b.Property<DateTime?>("ToolUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("tool_updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ToolId")
                        .HasName("PK__BotTool__28DE264FCEAE5617");

                    b.HasIndex(new[] { "ToolName" }, "UQ__BotTool__07C78DB8FC64FE8A")
                        .IsUnique();

                    b.ToTable("BotTool", (string)null);

                    b.HasData(
                        new
                        {
                            ToolId = 1,
                            ToolActive = true,
                            ToolCreatedAt = new DateTime(2025, 10, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            ToolDescription = "Tool to search for information from the internet.",
                            ToolName = "google_search",
                            ToolUpdatedAt = new DateTime(2025, 10, 25, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("chatBotIaCore.Domain.Models.Chat", b =>
                {
                    b.Property<int>("ChaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cha_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChaId"));

                    b.Property<DateTime?>("ChaCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("cha_created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ChaHistory")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cha_history");

                    b.Property<int>("ChaStatus")
                        .HasColumnType("int")
                        .HasColumnName("cha_status");

                    b.Property<DateTime?>("ChaUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("cha_updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ConId")
                        .HasColumnType("int")
                        .HasColumnName("con_id");

                    b.Property<int?>("UseId")
                        .HasColumnType("int")
                        .HasColumnName("use_id");

                    b.HasKey("ChaId")
                        .HasName("PK__Chat__5AF8FDEABAC1FF42");

                    b.HasIndex("ConId");

                    b.HasIndex("UseId");

                    b.ToTable("Chat", (string)null);
                });

            modelBuilder.Entity("chatBotIaCore.Domain.Models.Contact", b =>
                {
                    b.Property<int>("ConId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("con_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConId"));

                    b.Property<DateTime?>("ConCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("con_created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ConDisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("con_display_name");

                    b.Property<string>("ConExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("con_external_id");

                    b.Property<bool>("ConIsBlocked")
                        .HasColumnType("bit")
                        .HasColumnName("con_is_blocked");

                    b.Property<bool>("ConIsClient")
                        .HasColumnType("bit")
                        .HasColumnName("con_is_client");

                    b.Property<string>("ConPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("con_phone_number");

                    b.Property<string>("ConProfilePicPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("con_profile_pic_path");

                    b.Property<int>("ConType")
                        .HasColumnType("int")
                        .HasColumnName("con_type");

                    b.HasKey("ConId")
                        .HasName("PK__Contact__081B0F1AA8EA22A9");

                    b.HasIndex(new[] { "ConExternalId" }, "UQ__Contact__DDF265E034CC33A2")
                        .IsUnique();

                    b.ToTable("Contact", (string)null);

                    b.HasData(
                        new
                        {
                            ConId = 1,
                            ConCreatedAt = new DateTime(2025, 10, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            ConDisplayName = "Pedro Assenção",
                            ConExternalId = "557988132044",
                            ConIsBlocked = false,
                            ConIsClient = true,
                            ConPhoneNumber = "557988132044",
                            ConType = 1
                        });
                });

            modelBuilder.Entity("chatBotIaCore.Domain.Models.Message", b =>
                {
                    b.Property<int>("MesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mes_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MesId"));

                    b.Property<int>("ChaId")
                        .HasColumnType("int")
                        .HasColumnName("cha_id");

                    b.Property<int?>("ConId")
                        .HasColumnType("int")
                        .HasColumnName("con_id");

                    b.Property<string>("MesContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mes_content");

                    b.Property<DateTime?>("MesCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("mes_created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MesExternalId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mes_external_id");

                    b.Property<string>("MesOriginalPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("mes_original_path");

                    b.Property<string>("MesProcessedContent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mes_processed_content");

                    b.Property<int>("MesRole")
                        .HasColumnType("int")
                        .HasColumnName("mes_role");

                    b.Property<int?>("UseId")
                        .HasColumnType("int")
                        .HasColumnName("use_id");

                    b.HasKey("MesId")
                        .HasName("PK__Messages__86A20DC3A5F6115C");

                    b.HasIndex("ChaId");

                    b.HasIndex("ConId");

                    b.HasIndex("UseId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("chatBotIaCore.Domain.Models.ToolParameter", b =>
                {
                    b.Property<int>("ParamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("param_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParamId"));

                    b.Property<DateTime?>("ParamCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("param_created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ParamDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("param_description");

                    b.Property<string>("ParamName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("param_name");

                    b.Property<bool>("ParamRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("param_required");

                    b.Property<string>("ParamType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("param_type");

                    b.Property<int>("ToolId")
                        .HasColumnType("int")
                        .HasColumnName("tool_id");

                    b.HasKey("ParamId")
                        .HasName("PK__ToolPara__9282B816DCE47099");

                    b.HasIndex("ToolId");

                    b.ToTable("ToolParameter", (string)null);

                    b.HasData(
                        new
                        {
                            ParamId = 1,
                            ParamCreatedAt = new DateTime(2025, 10, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            ParamDescription = "One or multiple queries to Google Search.",
                            ParamName = "queries",
                            ParamRequired = true,
                            ParamType = "ARRAY",
                            ToolId = 1
                        });
                });

            modelBuilder.Entity("chatBotIaCore.Domain.Models.UseCase", b =>
                {
                    b.Property<int>("UcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("uc_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UcId"));

                    b.Property<int>("BotId")
                        .HasColumnType("int")
                        .HasColumnName("bot_id");

                    b.Property<DateTime?>("UcCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("uc_created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UcName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("uc_name");

                    b.Property<string>("UcSpecialPrompt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("uc_special_prompt");

                    b.Property<string>("UcTriggerKeywords")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("uc_trigger_keywords");

                    b.Property<DateTime?>("UcUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("uc_updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("UcId")
                        .HasName("PK__UseCase__9A4528808973FB5D");

                    b.HasIndex("BotId");

                    b.HasIndex(new[] { "UcName" }, "UQ__UseCase__0F2EF8FDC1861977")
                        .IsUnique();

                    b.ToTable("UseCase", (string)null);

                    b.HasData(
                        new
                        {
                            UcId = 1,
                            BotId = 1,
                            UcCreatedAt = new DateTime(2025, 10, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            UcName = "General Summary and Help",
                            UcSpecialPrompt = "You are engaging in a general conversation with a customer. Be polite and concise.",
                            UcTriggerKeywords = "",
                            UcUpdatedAt = new DateTime(2025, 10, 25, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("chatBotIaCore.Domain.Models.UseCaseToolMapping", b =>
                {
                    b.Property<int>("UcId")
                        .HasColumnType("int")
                        .HasColumnName("uc_id");

                    b.Property<int>("ToolId")
                        .HasColumnType("int")
                        .HasColumnName("tool_id");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_default");

                    b.HasKey("UcId", "ToolId")
                        .HasName("PK__UseCaseT__78C8CAE449D63D06");

                    b.HasIndex("ToolId");

                    b.ToTable("UseCaseToolMapping", (string)null);

                    b.HasData(
                        new
                        {
                            UcId = 1,
                            ToolId = 1,
                            IsDefault = true
                        });
                });

            modelBuilder.Entity("chatBotIaCore.Domain.Models.User", b =>
                {
                    b.Property<int>("UseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("use_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UseId"));

                    b.Property<DateTime?>("UseCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("use_created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UseEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("use_email");

                    b.Property<string>("UseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("use_name");

                    b.Property<string>("UsePasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("use_password_hash");

                    b.Property<string>("UsePhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("use_phone_number");

                    b.HasKey("UseId")
                        .HasName("PK__User__C00A8D83911314FD");

                    b.HasIndex(new[] { "UseEmail" }, "UQ__User__221F843AC00B422F")
                        .IsUnique();

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            UseId = 1,
                            UseCreatedAt = new DateTime(2025, 10, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            UseEmail = "pedro31@gmail.com",
                            UseName = "PedroAssencao",
                            UsePasswordHash = "pedro.123",
                            UsePhoneNumber = "5579988132044"
                        });
                });

            modelBuilder.Entity("chatBotIaCore.Domain.Models.Chat", b =>
                {
                    b.HasOne("chatBotIaCore.Domain.Models.Contact", "Con")
                        .WithMany("Chats")
                        .HasForeignKey("ConId")
                        .IsRequired()
                        .HasConstraintName("FK_Chat_Contact");

                    b.HasOne("chatBotIaCore.Domain.Models.User", "Use")
                        .WithMany("Chats")
                        .HasForeignKey("UseId")
                        .HasConstraintName("FK_Chat_User");

                    b.Navigation("Con");

                    b.Navigation("Use");
                });

            modelBuilder.Entity("chatBotIaCore.Domain.Models.Message", b =>
                {
                    b.HasOne("chatBotIaCore.Domain.Models.Chat", "Cha")
                        .WithMany("Messages")
                        .HasForeignKey("ChaId")
                        .IsRequired()
                        .HasConstraintName("FK_Messages_Chat");

                    b.HasOne("chatBotIaCore.Domain.Models.Contact", "Con")
                        .WithMany("Messages")
                        .HasForeignKey("ConId")
                        .HasConstraintName("FK_Messages_Contact");

                    b.HasOne("chatBotIaCore.Domain.Models.User", "Use")
                        .WithMany("Messages")
                        .HasForeignKey("UseId")
                        .HasConstraintName("FK_Messages_User");

                    b.Navigation("Cha");

                    b.Navigation("Con");

                    b.Navigation("Use");
                });

            modelBuilder.Entity("chatBotIaCore.Domain.Models.ToolParameter", b =>
                {
                    b.HasOne("chatBotIaCore.Domain.Models.BotTool", "Tool")
                        .WithMany("ToolParameters")
                        .HasForeignKey("ToolId")
                        .IsRequired()
                        .HasConstraintName("FK_ToolParameter_BotTool");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("chatBotIaCore.Domain.Models.UseCase", b =>
                {
                    b.HasOne("chatBotIaCore.Domain.Models.BotConfiguration", "Bot")
                        .WithMany("UseCases")
                        .HasForeignKey("BotId")
                        .IsRequired()
                        .HasConstraintName("FK_UseCase_BotConfiguration");

                    b.Navigation("Bot");
                });

            modelBuilder.Entity("chatBotIaCore.Domain.Models.UseCaseToolMapping", b =>
                {
                    b.HasOne("chatBotIaCore.Domain.Models.BotTool", "Tool")
                        .WithMany("UseCaseToolMappings")
                        .HasForeignKey("ToolId")
                        .IsRequired()
                        .HasConstraintName("FK_UCTM_BotTool");

                    b.HasOne("chatBotIaCore.Domain.Models.UseCase", "Uc")
                        .WithMany("UseCaseToolMappings")
                        .HasForeignKey("UcId")
                        .IsRequired()
                        .HasConstraintName("FK_UCTM_UseCase");

                    b.Navigation("Tool");

                    b.Navigation("Uc");
                });

            modelBuilder.Entity("chatBotIaCore.Domain.Models.BotConfiguration", b =>
                {
                    b.Navigation("UseCases");
                });

            modelBuilder.Entity("chatBotIaCore.Domain.Models.BotTool", b =>
                {
                    b.Navigation("ToolParameters");

                    b.Navigation("UseCaseToolMappings");
                });

            modelBuilder.Entity("chatBotIaCore.Domain.Models.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("chatBotIaCore.Domain.Models.Contact", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("chatBotIaCore.Domain.Models.UseCase", b =>
                {
                    b.Navigation("UseCaseToolMappings");
                });

            modelBuilder.Entity("chatBotIaCore.Domain.Models.User", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
